### PR TITLE
tests are now mocha-patible

### PR DESCRIPTION
**Pull request by hallas**

### CODE REVIEW

**Comment by jonathanong** [comment]
i did this on purpose because i wanted the tests to work with coffeescript (the original code). would this work with coffeescript?

**Comment by jonathanong** [comment]
and you got to fix `make test` so that it works with travis

**Comment by jonathanong** [comment]
haha i just noticed i have a convert to mocha issue. hmmm

**Comment by hallas** [comment]
yeah, lol, im confused by your issues ;)

**Comment by jonathanong** [comment]
whatever :D fix the makefile and i'll merge it. at least it'll look pretty

**Comment by hallas** [comment]
@jonathanong ping

**Comment by jonathanong** [comment]
too lazy to complain about squashing :P

**Comment by hallas** [comment]
hmm, im not sure what you mean, squashing commits? Please explain, (teach a man to fish you know... even though you're lazy)

**Comment by jonathanong** [comment]
oh. generally on simple pull requests, you should squash all the commits in a pull request into a single commit. if it's a complicated pull request, you would squash all the "fixes" and each commit should make sense on their own. ie, you won't have any commits that are like "fix typo" or "oops". 

it just makes the commit history look nicer. ideally, every single commit to a repo should be done like this (minus github's PR process), but it just takes a lot of effort. some people like node core also `pull` directly using `git` so the commit history isn't polluted with `merged pull request #xxxx`.

**Comment by hallas** [comment]
thanks, I understand

**Pull request merged**
